openapi: 3.0.3
info:
  title: API Action
  # description: An action that allows the user to create and manage a TODO list using a GPT.
  description: An action that allow the GPT to answer the user questions about specipic information found in the database.
  version: 'v1'
servers:
  - url: https://API.snps.it
paths:
  /todos:
    get:
      operationId: getTodos
      summary: Get the list of todos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
components:
  schemas:
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.