service: snps-otello-chatbot
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 30
  profile: snps
  region: eu-central-1
  httpApi:
    cors: true

functions:
  app:
    handler: app.server
    environment:
      OPENAI_API_KEY: ${ssm:/otello-chatbot/${sls:stage}/openai_api_key}
    package:
      individually: true
      exclude:
        - "./.env"
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /askGPT
          method: POST
          cors: true
    timeout: 29
    