service: snps-otello-chatbot
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}  # before goning to prod, consider changing logicaAPI url
  logRetentionInDays: 30
  profile: snps
  region: eu-central-1
  httpApi:
    cors: true

useDotenv: true

functions:
  app:
    handler: app.server
    environment:
      OPENAI_API_KEY: ${ssm:/otello-chatbot/${sls:stage}/openai_api_key}
      FINETUNED_MODEL_ID: ft:gpt-4o-mini-2024-07-18:personal::Adv9wIx1  # v2
      ASSISTANT_ID: asst_YJTAwcxcQ5Pks3dK7Q6ZjJTl  # dev
      VECTOR_STORE_ID: vs_6839bbd21e8481918fca67314f4f3452  # dev
      # ASSISTANT_ID: asst_xkM3V2sEngbh8y1wvKw2WDRJ  # prod
      # VECTOR_STORE_ID: vs_6839bc2200bc819190fa8628c2a64685  # prod
    package:
      individually: true
      exclude:
        - "./.env"
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /askGPT
          method: POST
          cors: true
    timeout: 29
    